version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Thêm volume để đồng bộ hóa mã nguồn cục bộ với container
    depends_on:
      - db
    environment:
      FLASK_ENV: development  # Thiết lập biến môi trường cho Flask

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
